### ISSUE TITLE
Design logo for back2work

### ISSUE THREAD

**Issue by sunnybansal** [back-to-work/back2workWebApp#4]
A logo should be designed for back2work org.

**Comment by p-disha** [comment]
Link to logo: https://drive.google.com/open?id=12FkaICrZowJXOmwQf2O26QwU9H0DGVTy

**Comment by sunnybansal** [comment]
There are some comments added for logo, @aishwaryakore5696 had a discussion with Professor and she'll be making required changes. Aishwarya please share more information if necessary.

**Comment by aishwaryakore5696** [comment]
These are the two final logos
![business](https://user-images.githubusercontent.com/57730651/83101309-09dda480-a080-11ea-90e8-0161f9179438.PNG)
![final](https://user-images.githubusercontent.com/57730651/83101318-106c1c00-a080-11ea-94da-be1ed77f170d.PNG)

**Comment by aishwaryakore5696** [comment]
Here is the link to the final logos-
https://drive.google.com/drive/folders/1bE8mmpYL_sz2hgsX8QOnCcVJ8tcDmz27?usp=sharing
